### ISSUE TITLE
tarea infografia

### ISSUE THREAD

**Issue by JulioCGz** [SistemasTecTlaxiaco/infografia-JulioCGz#2]
[sistemas (1).pdf](https://github.com/SistemasTecTlaxiaco/infografia-JulioCGz/files/7125432/sistemas.1.pdf)

**Comment by Erick-3as** [comment]
estaba bueno tu trabajo, pero lo único que te falto es justificar tus texto, y yo te doy un 18%

**Comment by josealfredo79** [comment]
De acuerdo a rúbrica se evaluó...??Bien hecho y revisado

**Comment by josealfredo79** [comment]
Bien hecho y revisado
